server:
  port: 8080

spring:
  #1.jdbc config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid:
    #old mysql driver
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/mydemo?characterEncoding=utf8&useOldAliasMetadataBehavior=true&allowMultiQueries=true&useSSL=false
    username: root
    password: wenxue
    initialSize: 5
    minIdle: 3
    maxActive: 8
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis= 5000
    connection-timeout: 300000


    redis:
      host: redis
      port: 31501
      #password: by321qaz
      database: 0
      timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
      # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      jedis:
        pool:
          # 最大空闲连接数
          max-idle: 100
          # 最小空闲连接数
          min-idle: 20
          # 等待可用连接的最大时间，负数为不限制
          max-wait: -1s
          # 最大活跃连接数，负数为不限制
          max-active: -1